// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlaiPOTlTFY1epeZIwz6JILZcUmeErKo',
    appId: '1:781246548343:web:8308cb3d1a41234cbfb972',
    messagingSenderId: '781246548343',
    projectId: 'passwrd-mngmnt',
    authDomain: 'passwrd-mngmnt.firebaseapp.com',
    storageBucket: 'passwrd-mngmnt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQlqcmJE-Wl2iMPPTeIu8x-8ozfKciCkI',
    appId: '1:781246548343:android:e41b2e873f12eee6bfb972',
    messagingSenderId: '781246548343',
    projectId: 'passwrd-mngmnt',
    storageBucket: 'passwrd-mngmnt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrrSSj1ex57weI_mSG74lYYC4XJdT5fk',
    appId: '1:781246548343:ios:f4b8cf3aa9034442bfb972',
    messagingSenderId: '781246548343',
    projectId: 'passwrd-mngmnt',
    storageBucket: 'passwrd-mngmnt.appspot.com',
    iosBundleId: 'com.example.passwordManagement',
  );
}
